version: '3'
services:

  postgres:
    image: postgres

  ansible:
    image: ansible/ansible:default
    volumes: 
      - data:/main/temp

  django:
    container_name: questionableansible
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/main/code
      - data:/main/temp
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - postgres
      - ansible

volumes:
  data: