# Generated by Django 2.0.10 on 2019-02-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionableansible', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcpinfo',
            name='user',
        ),
    ]
